import Head from "next/head";
import Header from "@/components/Header";
import styles from "../styles/style.module.scss";
import Timeline from "@/components/Timeline";
import Post from "@/components/Post";
import { useEffect, useState } from "react";
import apiClient from "@/lib/apiClient";
import { useRouter } from "next/navigation"; // 追加

export type User = {
  id: number;
  username: string;
  email: string;
  password: string;
};

export type Post = {
  id: number;
  content: string;
  createdAt: string;
  authorId: number;
  author: User;
}; 


export default function Home() {
  // useState に型を適用
  const [posts, setPosts] = useState<Post[]>([]);
  const router = useRouter(); //  ルーターを取得

  // useEffectの処理=画面が表示された直後に１度実行されます🤗
  useEffect(() => {
    const fetchPosts = async () => {
      try {
        const response = await apiClient.get("/api/posts");
        console.log(response, "response"); //取得できているかチェックしてみましょう🤗
        setPosts(response.data);
      } catch (error) {
        console.error("投稿の取得に失敗しました:", error);
      }
    };

    fetchPosts();
  }, [router]);

  // 追加
  console.log(posts, "データ");
  // useEffect
  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <Header />
        <Timeline setPosts={setPosts} />
           {posts.map((item, index) => (
          <Post
            key={index}
            content={item.content}
            createdAt={item.createdAt}
            author={item.author}
          />
        ))}
      </main>
    </>
  );
}
